from __future__ import annotations

from .project_helpers import (
    FileSummary,
    build_tree_snapshot,
    classify_file,
    common_repo_path,
    create_scan,
    dedupe_symbols,
    describe_layout,
    detect_contract_symbols,
    detect_symbols,
    ensure_column,
    feature_area,
    feature_area_groups,
    file_is_current,
    file_role,
    finish_scan,
    generic_file_role,
    important_packages,
    infer_purpose,
    infer_stack,
    inferred_project_facts,
    is_important_file,
    iter_project_files,
    key_responsibilities,
    line_number,
    major_responsibilities,
    mark_deleted_files,
    minimal_rule_files,
    record_decision,
    rebuild_project_layers,
    rebuild_read_rules,
    refresh_staleness,
    related_files,
    relative_to_any,
    replace_symbols,
    resolve_allowed_path,
    route_from_svelte_path,
    row_dict,
    rule_file_priority,
    seed_current_task,
    seed_decisions,
    set_verified_fact,
    slugify,
    split_csv,
    stable_project_id,
    summarize_file,
    symbol_contract,
    top_level_config_keys,
    update_project_profile_field,
    update_project_purpose,
    update_task,
    upsert_file,
    verified_project_facts,
    when_to_read,
)
from .project_indexer import index_project, project_has_completed_scan
from .project_overrides import (
    ARCHITECTURE_FIELDS,
    PROJECT_OVERVIEW_FIELDS,
    apply_list_overrides,
    apply_project_memory_overrides,
    apply_symbol_overrides,
    filtered_text_fields,
    load_project_memory_overrides,
    project_overview_update,
    record_project_note,
    required_text,
    save_project_memory_override,
    string_list,
    symbol_contract_key,
    update_structured_project_memory,
)
from .project_registry import (
    ensure_global_database,
    find_project_by_canonical_path,
    list_projects,
    load_project,
    project_list_context,
    register_project,
    unregister_project,
    upsert_global_project,
)
from .project_schema import initialize_project_database
from .project_specs import (
    archive_project_spec,
    active_project_specs,
    create_project_spec,
    list_project_specs,
    read_project_spec,
    spec_to_json,
    update_project_spec,
)
from .project_types import (
    LOGGER,
    MAX_FILE_BYTES,
    SKIP_DIRS,
    SKIP_SUFFIXES,
    SYMBOL_PATTERNS,
    IndexResult,
    Project,
)
from .project_views import project_brief, project_map, project_model
